# Generated by Django 5.1.2 on 2024-11-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passwoed_encrypted',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
