# Generated by Django 5.1.2 on 2024-12-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_alter_engagement_status_alter_tagsexps_experiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=models.CharField(choices=[('finish', '已完成'), ('to-qualify-user', '用户资质待审核'), ('to-check-result', '实验结果待审核')], max_length=24),
        ),
    ]
