# Generated by Django 5.1.2 on 2024-12-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0003_alter_engagement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
