# Generated by Django 5.1.2 on 2024-12-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataUserLogin',
        ),
        migrations.DeleteModel(
            name='DataUserRegister',
        ),
    ]
