# Generated by Django 5.1.2 on 2024-12-26 01:13

import django.core.validators
import django.db.models.deletion
import utils.generate_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_delete_datauserlogin_delete_datauserregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='media/avatar/user_0/default_avatar.png', upload_to=utils.generate_path.GeneratePath.generate_path_avatar),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ongoing', '进行中'), ('finish', '已完成')], max_length=12)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
