# Generated by Django 5.1.2 on 2024-10-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
