# Generated by Django 5.1.2 on 2024-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0006_remove_userprofile_owner_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password_encrypted', models.CharField(max_length=1024)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataUserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password_encrypted', models.CharField(max_length=1024)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
