name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    if: false
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Use NPM Mirror
        run: npm config set registry https://registry.npmmirror.com

      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: ./frontend/node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Pages
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          force_orphan: true
